# Generated by Django 5.2.5 on 2025-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Für')),
                ('create_by', models.CharField(max_length=20, verbose_name='Von')),
                ('title', models.CharField(blank='false', max_length=40, verbose_name='Task')),
                ('status', models.CharField(max_length=20, verbose_name='Stauts')),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
