# Generated by Django 5.2.5 on 2025-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_by',
            field=models.CharField(max_length=100, verbose_name='Von'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Für'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Stauts'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank='false', max_length=120, verbose_name='Task'),
        ),
    ]
